--- #YAML:1.0
name:                Compass-Bearing
version:             0.07
abstract:            Convert angle to text bearing (aka heading)
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    GD::Graph::Polar:              0.09
    Geo::Functions:                0.03
    Package::New:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
